### ISSUE TITLE
Reset button?

### ISSUE THREAD

**Issue by fdncred** [nushell/demo#26]
I seem to get it into a state where no command is interpreted any longer. I can click the top buttons and they put text in the window but if I hit run or ctrl/cmd-enter nothing happens. There are no errors visible. So, would it be possible to have some type of a reset button? I'm not sure what that would do since when this happens today I have to ctrl-c out and do `npm start` again.

**Comment by jzaefferer** [comment]
There's various errors that aren't handled properly, one category is covered by #12. I have no idea how to recover from those, since the wasm process or worker or whatever it is seems to kinda crash.

For me its enough to reload the page to get back to a working state.

So I think this needs to be addressed by improved error handling.

**Comment by jonathandturner** [comment]
@jzaefferer - if the commands don't work, should we just not show them?  I think you were saying you wanted to show them but just have them error when you use them

**Comment by jzaefferer** [comment]
Yes, I think "not supported in the browser (via WebAssembly)" is better in this demo than pretending that the command doesn't exist.

**Comment by jonathandturner** [comment]
Maybe we can make the list, like you're doing, and register these commands to return that message. As we start to make them work in wasm, we can remove this shim error registration.

**Comment by jzaefferer** [comment]
That sounds good to me!

**Comment by jzaefferer** [comment]
I think the WIP notice and eventually dealing with #12 is going to take care of this.
